config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  post 'top/login'
  root 'top#main'
  post 'top/logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/top.rb
class Top < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid]
      render :main
    else
      render :login
    end 
  end

  def login
    if Top.find_by(uid: params[:uid], pass: params[:pass])
      session[:login_uid] = params[:uid]
      redirect_to root_path
    else
      render :error
    end 
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
ログイン失敗です!
<p>
    <%= link_to '戻る', :back %>
</p>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
<%= label_tag :uid, 'ユーザーID' %>
<%= text_field_tag :uid %>
<p><%= label_tag :pass, 'パスワード' %>
<%= password_field_tag :pass %></p>

<%= submit_tag '登録' %>
<% end %>

app/views/top/main.html.erb
ログイン成功です
<p>
    <%= link_to 'ログアウト', top_logout_path, method: :post %>
</p>